# Generated by Django 5.1.2 on 2024-10-23 22:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fantasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='fantasias/')),
                ('participant', models.CharField(verbose_name='Participante')),
                ('name', models.TextField(verbose_name='Fantasia')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('fantasy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.fantasy')),
            ],
        ),
    ]
